const NodeRedConfig = {
  comment: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/comment.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: false,
    fill: "#f3f3f3",
  },
  debug: {
    prefixImage: "",
    suffixImage: "http://124.222.40.17:1880/icons/node-red/debug.svg",
    socketIn: false,
    socketOut: true,
    inPort: true,
    outPort: false,
    fill: "#87a980",
  },
  inject: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/inject.svg",
    suffixImage: "",
    socketIn: true,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#a6bbcf",
  },
  complete: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/alert.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#c0edc0",
  },
  status: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/status.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#94c1d0",
  },
  "link in": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/link-out.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#d3d3d3",
  },
  "link call": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/link-call.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#d3d3d3",
  },
  catch: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/alert.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#e49191",
  },
  "link out": {
    prefixImage: "",
    suffixImage: "http://124.222.40.17:1880/icons/node-red/link-out.svg",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "#d3d3d3",
  },
  function: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/function.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#fdd0a2",
  },
  switch: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/switch.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  change: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/swap.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  range: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/range.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  template: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/template.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(243, 181, 103)",
  },
  delay: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/timer.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E6E0F8",
  },
  trigger: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/trigger.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E6E0F8",
  },
  exec: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/cog.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: 3,
    fill: "darksalmon",
    height: 45,
  },
  rbe: {
    label: "filter",
    prefixImage: "http://124.222.40.17:1880/icons/node-red/rbe.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  "moving-average": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/moving-average.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  "mqtt in": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/bridge.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#d8bfd8",
  },
  "mqtt out": {
    prefixImage: "",
    suffixImage: "http://124.222.40.17:1880/icons/node-red/bridge.svg",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "#d8bfd8",
  },
  "http in": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/white-globe.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "rgb(231, 231, 174)",
  },
  "http response": {
    prefixImage: "",
    suffixImage: "http://124.222.40.17:1880/icons/node-red/white-globe.svg",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(231, 231, 174)",
  },
  "http request": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/white-globe.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(231, 231, 174)",
  },
  "websocket in": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/white-globe.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "rgb(231, 231, 174)",
  },
  "websocket out": {
    prefixImage: "",
    suffixImage: "http://124.222.40.17:1880/icons/node-red/white-globe.svg",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(231, 231, 174)",
  },
  "tcp in": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/bridge.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#d3d3d3",
  },
  "tcp out": {
    prefixImage: "",
    suffixImage: "http://124.222.40.17:1880/icons/node-red/bridge.svg",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "#d3d3d3",
  },
  "tcp request": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/bridge.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#d3d3d3",
  },
  "udp in": {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/bridge.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "#d3d3d3",
  },
  "udp out": {
    prefixImage: "",
    suffixImage: "http://124.222.40.17:1880/icons/node-red/bridge.svg",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "#d3d3d3",
  },
  split: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/split.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  join: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/join.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  sort: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/sort.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  batch: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/batch.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#E2D96E",
  },
  csv: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/parser-csv.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#DEBD5C",
  },
  html: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/parser-html.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#DEBD5C",
  },
  json: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/parser-json.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#DEBD5C",
  },
  xml: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/parser-xml.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#DEBD5C",
  },
  yaml: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/parser-yaml.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#DEBD5C",
  },
  file: {
    label: "write file",
    prefixImage: "http://124.222.40.17:1880/icons/node-red/file-out.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "BurlyWood",
  },
  "file in": {
    label: "read file",
    prefixImage: "http://124.222.40.17:1880/icons/node-red/file-in.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "BurlyWood",
  },
  watch: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/watch.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: false,
    outPort: true,
    fill: "BurlyWood",
  },
  "influxdb in": {
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-contrib-influxdb/influxdb.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(218, 196, 180)",
  },
  mysql: {
    prefixImage: "http://124.222.40.17:1880/icons/node-red/db.svg",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "#e97b00",
  },
  "influxdb out": {
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-contrib-influxdb/influxdb.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(218, 196, 180)",
  },
  "influxdb batch": {
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-contrib-influxdb/influxdb.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(218, 196, 180)",
  },
  ui_button: {
    label: "button",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_button.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_dropdown: {
    label: "dropdown",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_dropdown.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_switch: {
    label: "switch",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_switch.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_slider: {
    label: "slider",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_slider.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_numeric: {
    label: "numeric",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_numeric.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_text_input: {
    label: "text input",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_text_input.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_date_picker: {
    label: "date picker",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_date_picker.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_colour_picker: {
    label: "colour picker",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_colour_picker.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_form: {
    label: "form",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_form.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(176, 223, 227)",
  },
  ui_text: {
    label: "text",
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_text.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(119, 198, 204)",
  },
  ui_gauge: {
    label: "gauge",
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_gauge.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(119, 198, 204)",
  },
  ui_chart: {
    label: "chart",
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_chart.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb(119, 198, 204)",
  },
  ui_audio: {
    label: "audio out",
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_audio.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(119, 198, 204)",
  },
  ui_toast: {
    label: "notification",
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_toast.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: false,
    fill: "rgb(119, 198, 204)",
  },
  ui_ui_control: {
    label: "ui control",
    prefixImage: "",
    suffixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_ui_control.png",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb( 63, 173, 181)",
  },
  ui_template: {
    label: "template",
    prefixImage:
      "http://124.222.40.17:1880/icons/node-red-dashboard/ui_template.png",
    suffixImage: "",
    socketIn: false,
    socketOut: false,
    inPort: true,
    outPort: true,
    fill: "rgb( 63, 173, 181)",
  },
};

export default NodeRedConfig;
