export const NodeTypes = [
  "comment",
  "debug",
  "inject",
  "complete",
  "status",
  "link in",
  "link call",
  "catch",
  "link out",
  "function",
  "switch",
  "change",
  "range",
  "template",
  "delay",
  "trigger",
  "exec",
  "rbe",
  "moving-average",
  "mqtt in",
  "mqtt out",
  "http in",
  "http response",
  "http request",
  "websocket in",
  "websocket out",
  "tcp in",
  "tcp out",
  "tcp request",
  "udp in",
  "udp out",
  "split",
  "join",
  "sort",
  "batch",
  "csv",
  "html",
  "json",
  "xml",
  "yaml",
  "file",
  "file in",
  "watch",
  "influxdb in",
  "mysql",
  "influxdb out",
  "influxdb batch",
  "ui_button",
  "ui_dropdown",
  "ui_switch",
  "ui_slider",
  "ui_numeric",
  "ui_text_input",
  "ui_date_picker",
  "ui_colour_picker",
  "ui_form",
  "ui_text",
  "ui_gauge",
  "ui_chart",
  "ui_audio",
  "ui_toast",
  "ui_ui_control",
  "ui_template",
];

export const ConfigTypes = ["mqtt-broker", "influxdb", "websocket-client", "websocket-listener", "ui_group", "ui_tab"];
export const TabTypes = ["tab"];
